# Generated by Django 3.1.2 on 2020-10-09 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_text', models.CharField(max_length=255)),
                ('search_text', models.CharField(max_length=255)),
                ('conversation', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('in_response_to', models.CharField(max_length=255)),
                ('search_in_response_to', models.CharField(max_length=255)),
                ('persona', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TagAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.statement')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.tag')),
            ],
        ),
    ]
